"""remove unique filesname

Revision ID: 757f303fc397
Revises: a1b2c3d4e5f6
Create Date: 2026-03-11 09:26:39.011603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '757f303fc397'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_menu_documents_filename'), 'menu_documents', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_menu_documents_filename'), 'menu_documents', ['filename'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
